parameters:
#    skylink_ebook_ges_ouvrages.example.class: SkylinkEbook\GesOuvragesBundle\Example

services:
#    skylink_ebook_ges_ouvrages.example:
#        class: %skylink_ebook_ges_ouvrages.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
