skylink_ebook_ges_user_login:
    path:     /login
    defaults: { _controller: SkylinkEbookGesUserBundle:GesUser:login }
    
skylink_ebook_ges_user_home:
    path:     /home
    defaults: { _controller: SkylinkEbookGesUserBundle:GesUser:home }
