parameters:
#    skylink_ebook_ges_commandes.example.class: SkylinkEbook\GesCommandesBundle\Example

services:
#    skylink_ebook_ges_commandes.example:
#        class: %skylink_ebook_ges_commandes.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
