parameters:
#    skylink_ebook_admin.example.class: SkylinkEbook\AdminBundle\Example

services:
#    skylink_ebook_admin.example:
#        class: %skylink_ebook_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
