parameters:
#    skylink_ebook_ges_organisation.example.class: SkylinkEbook\GesOrganisationBundle\Example

services:
#    skylink_ebook_ges_organisation.example:
#        class: %skylink_ebook_ges_organisation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
